Repository jlgranof/Galactic-Brite, pull requests merged in 2020-10, with the labels that each got.

#3 added test page
  .DS_Store
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/images/fighter.gif
  client/src/assets/images/galaxy.jpg
  client/src/assets/images/hanger.jpg
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderLogo.js
  client/src/components/Header/LeftHeaderLinks.js
  client/src/components/Header/RightHeaderLinks.js
  client/src/components/TestPage/TestPage.js
  client/src/index.css
Labels: enhancement

#24 error handler for no ids on events
  backend/api/event_routes.py
Labels: bug

#26 Events backend
  backend/models.py
  database.py
  star_wars_events.md
Labels: enhancement

#36 Kasey
  .vscode/settings.json
  Pipfile.lock
  backend/__init__.py
  backend/api/custom_events/event_randomizer.py
  backend/api/session_routes.py
  client/src/App.js
  client/src/actions/authActions.js
  client/src/actions/featuredActions.js
  client/src/components/CarouselComponent/CarouselComponent.js
  client/src/components/LoginComponent/LoginDialog.js
  postman.js
Labels: bug, enhancement

#40 added logged out
  client/src/actions/authActions.js
  client/src/components/Header/Header.js
  client/src/components/Header/RightHeaderLinks.js
  client/src/components/LoginComponent/LoginDialog.js
  client/src/index.css
Labels: enhancement

#45 Kasey
  client/src/App.js
  client/src/components/AboutUsPage/AboutUsPage.js
  client/src/components/Dashboard/Dashboard.js
  client/src/components/Header/Header.js
  client/src/components/Header/LeftHeaderLinks.js
  client/src/components/Header/RightHeaderLinks.js
  client/src/components/TestPage/TestPage.js
Labels: enhancement

#64 Kasey
  client/src/App.js
  client/src/actions/authActions.js
  client/src/actions/eventsActions.js
  client/src/actions/featuredActions.js
  client/src/assets/images/icon.png
  client/src/assets/images/icon10.png
  client/src/assets/images/icon2.png
  client/src/assets/images/icon3.png
  client/src/assets/images/icon4.png
  client/src/assets/images/icon5.png
  client/src/assets/images/icon6.png
  client/src/assets/images/icon7.png
  client/src/assets/images/icon8.png
  client/src/assets/images/icon9.png
  client/src/assets/images/somethingMissing.jpg
  client/src/components/CarouselComponent/CarouselItems.js
  client/src/components/CarouselComponent/FeaturedCarousel.js
  client/src/components/Create-New-Events/CreateEvent.js
  client/src/components/EventsComponent/EventsComponent.js
  client/src/components/FeaturedEventsComponent/FeaturedEventsComponent.js
  client/src/components/Footer/Footer.js
  client/src/components/LandingPage/LandingPage.js
  client/src/index.css
  client/src/reducers/FeaturedEvents.js
  client/src/store/ReduxStore.js
Labels: enhancement

#91 alter sign in and sign up
  client/src/Redux/actions/eventsActions.js
  client/src/Redux/reducers/FeaturedEvents.js
  client/src/components/CarouselComponent/FeaturedCarousel.js
  client/src/components/Dashboard/Dashboard.js
  client/src/components/EventDetails/EventDetails.js
  client/src/components/EventsComponent/EventsComponent.js
  client/src/components/FeaturedEventsComponent/FeaturedEventsComponent.js
  client/src/components/Header/Header.js
  client/src/components/Header/RightHeaderLinks.js
  client/src/components/LoginComponent/LoginDialog.js
  client/src/components/SignupComponent/SignupDialog.js
  client/src/components/SignupComponent/SignupModal.js
  client/src/index.css
Labels: enhancement
